"""Core video tracking logic using Ultralytics YOLO.

Processes a single video through the YOLO tracking pipeline, extracting
per-frame bounding boxes, track IDs, confidence scores, and class labels.
Results are saved in MOTChallenge format, with optional visualization.
"""

import os
import shutil
import time
import traceback
from glob import glob
from pathlib import Path

import numpy as np

from MOT.mot_writer import write_mot_results
from MOT.track_plotter import TrackPlotter
from MOT.video_utils import get_video_info


def process_video(
    model,
    video_path: str,
    video_output_dir: str,
    tracker: str = "botsort.yaml",
    conf: float = 0.25,
    iou: float = 0.7,
    save_vid: bool = False,
    plot_tracks: bool = False,
    trail_length: int = 30,
    device: str = "",
    classes: list[int] | None = None,
    imgsz: int = 640,
) -> dict:
    """Track all objects in a single video and save results.

    Runs YOLO object tracking frame-by-frame with persistent IDs,
    converts detections to MOTChallenge format, and writes output files.

    Args:
        model: Pre-loaded Ultralytics YOLO model instance.
        video_path: Path to the input video file.
        video_output_dir: Output directory for this video's results.
            Should already reflect the mirrored input directory structure.
        tracker: Tracker config file path. Can be a built-in name
            ("botsort.yaml", "bytetrack.yaml") or a path to a custom
            YAML file (e.g., one generated by tracker_config.py).
        conf: Detection confidence threshold (0.0-1.0). Detections below
            this score are discarded.
        iou: IoU threshold (0.0-1.0) for NMS and tracker association.
        save_vid: If True, save an annotated video with bounding boxes
            and track IDs (Ultralytics built-in rendering, no trajectories).
        plot_tracks: If True, save a video with bounding boxes, track IDs,
            AND trajectory lines showing each object's movement history.
            Can be used together with save_vid (produces two separate videos).
        trail_length: Number of past frames to draw trajectory lines for.
            Only used when plot_tracks=True. Default: 30.
        device: Device string for inference. Examples: "" (auto),
            "cpu", "0", "cuda:0".
        classes: Optional list of COCO class IDs to filter detections.
            E.g., [0] for person-only tracking. None tracks all classes.
        imgsz: Inference image size. The longer side of the input frame
            is scaled to this value (aspect ratio preserved with letterbox
            padding). Output coordinates are mapped back to original
            resolution. Larger values improve accuracy but reduce speed.

    Returns:
        Stats dict with keys:
            - video_name (str): Video filename stem.
            - video_path (str): Absolute path to the input video.
            - total_frames (int): Number of frames processed.
            - total_tracks (int): Number of unique track IDs assigned.
            - total_detections (int): Sum of detections across all frames.
            - processing_time_s (float): Wall-clock time in seconds.
            - fps (float): Processing speed (frames/second).
            - status (str): "success" or "failed".
            - error (str or None): Error message if failed.
            - traceback_str (str or None): Full traceback if failed.
            - video_info (dict or None): Video metadata dict.
            - output_txt (str or None): Path to MOT results file.
            - output_vid (str or None): Path to annotated video file.
            - output_trajectory_vid (str or None): Path to trajectory video.
    """
    video_path = os.path.abspath(video_path)
    video_name = Path(video_path).stem
    os.makedirs(video_output_dir, exist_ok=True)

    # Initialize stats with defaults for the failure case
    stats = {
        "video_name": video_name,
        "video_path": video_path,
        "total_frames": 0,
        "total_tracks": 0,
        "total_detections": 0,
        "processing_time_s": 0.0,
        "fps": 0.0,
        "status": "failed",
        "error": None,
        "traceback_str": None,
        "video_info": None,
        "output_txt": None,
        "output_vid": None,
        "output_trajectory_vid": None,
    }

    plotter = None

    try:
        # Get video metadata
        video_info = get_video_info(video_path)
        stats["video_info"] = video_info
        expected_frames = video_info["total_frames"]

        print(
            f"  Video: {video_info['width']}x{video_info['height']}, "
            f"{expected_frames} frames, {video_info['fps']:.1f} FPS, "
            f"{video_info['duration_s']}s"
        )

        # Initialize trajectory plotter if requested
        if plot_tracks:
            trajectory_path = os.path.join(
                video_output_dir, "tracked_trajectories.avi"
            )
            plotter = TrackPlotter(
                output_path=trajectory_path,
                width=video_info["width"],
                height=video_info["height"],
                fps=video_info["fps"],
                trail_length=trail_length,
            )

        # Run tracking
        start_time = time.time()

        # Build track kwargs; if save_vid, direct Ultralytics output
        # to our output directory to avoid polluting other projects.
        track_kwargs = dict(
            source=video_path,
            persist=True,
            stream=True,
            tracker=tracker,
            conf=conf,
            iou=iou,
            save=save_vid,
            device=device if device else None,
            classes=classes,
            imgsz=imgsz,
            verbose=False,
        )
        if save_vid:
            track_kwargs["project"] = video_output_dir
            track_kwargs["name"] = "."
            track_kwargs["exist_ok"] = True

        results_generator = model.track(**track_kwargs)

        all_results = []
        unique_track_ids = set()
        total_detections = 0
        frame_number = 0

        for result in results_generator:
            frame_number += 1

            if frame_number % 100 == 0 or frame_number == expected_frames:
                print(
                    f"\r  Processing: {frame_number}/{expected_frames} frames",
                    end="",
                    flush=True,
                )

            # Update trajectory plotter (processes all frames, even with
            # no detections, to keep video in sync)
            if plotter is not None:
                plotter.update(result)

            # Skip frames with no tracked objects for MOT output
            if result.boxes.id is None:
                continue

            # Extract tracking data
            xyxy = result.boxes.xyxy.cpu().numpy()
            track_ids = result.boxes.id.int().cpu().numpy()
            confs = result.boxes.conf.cpu().numpy()
            cls = result.boxes.cls.int().cpu().numpy()

            # Convert xyxy (x1, y1, x2, y2) to xywh (left, top, width, height)
            bb_left = xyxy[:, 0]
            bb_top = xyxy[:, 1]
            bb_width = xyxy[:, 2] - xyxy[:, 0]
            bb_height = xyxy[:, 3] - xyxy[:, 1]

            all_results.append({
                "frame": frame_number,
                "track_ids": track_ids,
                "bb_left": bb_left,
                "bb_top": bb_top,
                "bb_width": bb_width,
                "bb_height": bb_height,
                "confs": confs,
                "classes": cls,
            })

            unique_track_ids.update(track_ids.tolist())
            total_detections += len(track_ids)

        elapsed = time.time() - start_time
        print()  # newline after progress

        # Finalize trajectory video
        trajectory_vid_path = None
        if plotter is not None:
            trajectory_vid_path = plotter.close()
            plotter = None
            print(f"  Trajectory video: {trajectory_vid_path}")

        # Write MOT results
        txt_path = os.path.join(video_output_dir, "tracking_results.txt")
        write_mot_results(txt_path, all_results)

        # Move annotated video if saved by Ultralytics
        vid_path = None
        if save_vid:
            vid_path = _rename_ultralytics_video(video_path, video_output_dir)

        # Update stats for success
        stats.update({
            "total_frames": frame_number,
            "total_tracks": len(unique_track_ids),
            "total_detections": total_detections,
            "processing_time_s": round(elapsed, 2),
            "fps": round(frame_number / elapsed, 1) if elapsed > 0 else 0.0,
            "status": "success",
            "output_txt": txt_path,
            "output_vid": vid_path,
            "output_trajectory_vid": trajectory_vid_path,
        })

        print(
            f"  Done: {frame_number} frames, {len(unique_track_ids)} tracks, "
            f"{total_detections} detections, {elapsed:.1f}s ({stats['fps']} FPS)"
        )

    except Exception as e:
        stats["error"] = str(e)
        stats["traceback_str"] = traceback.format_exc()
        print(f"\n  FAILED: {e}")
    finally:
        # Ensure plotter is properly closed on error
        if plotter is not None:
            try:
                plotter.close()
            except Exception:
                pass

    return stats


def _rename_ultralytics_video(
    video_path: str, video_output_dir: str
) -> str | None:
    """Rename the annotated video saved by Ultralytics to a standard name.

    Ultralytics saves as <video_stem>.avi. This renames it to
    tracked_video.avi, keeping the original format as-is.

    Args:
        video_path: Original input video path (to match the filename).
        video_output_dir: Directory where Ultralytics saved the file.

    Returns:
        Path to the renamed video file, or None if not found.
    """
    video_stem = Path(video_path).stem

    # Find the Ultralytics output file
    candidates = glob(os.path.join(video_output_dir, f"{video_stem}.*"))
    video_exts = {".avi", ".mp4", ".mkv", ".mov"}
    candidates = [
        c for c in candidates
        if Path(c).suffix.lower() in video_exts
        and not os.path.basename(c).startswith("tracked_")
    ]

    if not candidates:
        print(f"  Warning: Could not find annotated video for {video_stem}")
        return None

    src = max(candidates, key=os.path.getmtime)
    ext = Path(src).suffix  # keep original extension (.avi)
    dst = os.path.join(video_output_dir, f"tracked_video{ext}")
    shutil.move(src, dst)
    print(f"  Annotated video: {dst}")
    return dst
